### ISSUE TITLE
Gather Requirments

### ISSUE THREAD

**Issue by myles** [pyconca/2016-web#1]
## New Features
- Speaker Signup Forms
- Google Calendar events for the schedule.
- Read Only JSON API Feed
- Slack bot/slashbot
- Email validation check
## Issues from last year
- Titles to long on the web site and the badges

**Comment by pdmccormick** [comment]
Myles, how about using something like [Pelican](http://docs.getpelican.com/en/3.6.3/) for static page generation from Markdown sources? Combined with automatic deployment from a Git push, we could more easily turn around small content changes to the site.
