### ISSUE TITLE
Fill in VIA convention code in the Venue Travel section

### ISSUE THREAD

**Issue by myles** [pyconca/2016-web#13]
- English: [web/markdown/venue-travel_en.markdown](/pyconca/2016-web/blob/master/web/markdown/venue-travel_en.markdown)
- French: [web/markdown/venue-travel_fr.markdown](/pyconca/2016-web/blob/master/web/markdown/venue-travel_fr.markdown)

**Comment by frdeso** [comment]
I submitted a request on the VIARail website. Waiting for the code.
