### ISSUE TITLE
Stephen J. Turnbull's photo needs to be rotated

### ISSUE THREAD

**Issue by myles** [pyconca/2016-web#58]
https://2016.pycon.ca/en/schedule/116-stephen-j-turnbull/

**Comment by avolkov** [comment]
This might be a display / html / png bug, as when you view image full screen, it's not rotated.

**Comment by myles** [comment]
It's because it's set in the meta data to be rotated and not actually
rotated.

**Comment by avolkov** [comment]
Here's image rotated, with stripped metadata.

I can replace it on pycon.ca site if someone could give me access to it.
![stephen-j-turnbull](https://cloud.githubusercontent.com/assets/648191/19499803/6526960e-9566-11e6-92a9-9aa2e5a8f44b.jpg)

**Comment by myles** [comment]
You already have access.

**Comment by avolkov** [comment]
pycon.ca ? 

I'm no wrong laptop. I'm gonna fix the image once I get home.

**Comment by avolkov** [comment]
Fixed in https://github.com/pyconca/2016-web/pull/61
